# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.
#
# ,--------.      ,--.   ,--. ,--.
# '--.  .--',---.  \  `.'  /,-'  '-.
#    |  |  | .-. :  .'    \ '-.  .-'
#    |  |  \   --. /  .'.  \  |  |
#    `--'   `----''--'   '--' `--'




## => Site Settings
##############################
text_color_theme: default # "default" (default), "dark", "forest", "ocean", "chocolate", "orange"
url: # the base hostname & protocol for your site e.g. https://www.someone.com
baseurl: # does not include hostname
title: IMROK
description: > # this means to ignore newlines until "Language & timezone"
  IMROK


## => Language and Timezone
##############################
lang: kr # the language of your site, "en" (default, English), "zh"(简体中文), "zh-Hans"(简体中文), "zh-Hant"(繁體中文)
timezone: Asia/Seoul # see https://en.wikipedia.org/wiki/List_of_tz_database_time_zones for the available values


## => Author and Social
##############################
author:
  name: 김형록
  email: q0115643@kaist.ac.kr # your Email address e.g. someone@site.com
  facebook: 100004915320124 # your Facebook username
  #twitter: # your Twitter username
  github: q0115643 # your GitHub username
  #linkedin: # your Linkedin username
  #googleplus: # your Google+ username
  #weibo: # your Weibo username
  #douban: # your Douban username


## => GitHub Repository (if the site is hosted by GitHub)
##############################
repository: q0115643/my_blog
repository_tree: master


## => Navigation
##############################
paths:
  base: /
  home: /
  pieces: /pieces.html
  all:  /all.html
  rss:  /feed.xml

nav_lists:
  - titles:
      en: About
      kr: 소개
      zh: 关于
      zh-Hans: 关于
      zh-Hant: 關於
    url: /about.html


## => Post
##############################
## excerpt
excerpt_separator: <!--more-->
excerpt_type: html # text (default), html

## TOC
toc:
  selectors: "h1,h2,h3" # "h1,h2,h3" (default)

## Markdown Enhancements

# Mathjax
mathjax: true # false (default), true
mathjax_autoNumber: true # false (default), true

# Mermaid
mermaid: true # false (default), true

# Chart
chart: true # false (default), true


## => Paginate
##############################
paginate: 5
paginate_path: /blog/page:num # don't change this unless for special need


## => Sources
##############################
sources: bootcdn # bootcdn (default), unpkg


## => Comments
##############################
## Disqus
disqus:
  shortname: rokrokss # the Disqus shortname for the site

## Gitalk
# please refer to https://github.com/gitalk/gitalk for more info.
gitalk:
  #clientID: 143666b578a416f82175 # GitHub Application Client ID
  #clientSecret: 1d1c0604a1a4bff9b59ab7f56724dc0e8b837775 # GitHub Application Client Secret
  #repository: gitalk-demo # GitHub repo
  #owner: q0115643 # GitHub repo owner
  #admin: # GitHub repo owner and collaborators, only these guys can initialize GitHub issues, IT IS A LIST.
    # - q0115643


## => Pageview
##############################
## Leancloud
leancloud:
  app_id: gg2EhhsosMcQOBEApofBaScO-gzGzoHsz # LeanCloud App id
  app_key: H1s5eqBlwLcHWuma9D8lFajn # LeanCloud App key
  app_class: rokrok # LeanCloud App class


## => Analytics
##############################
## Google Analytics
ga_tracking_id: UA-111579778-1 # Google Analytics id for the site


## => Build
##############################
markdown: kramdown
highlighter: rouge
permalink: date

exclude:
  - CHANGELOG.md
  - CHECKLIST.md
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README-*.md
  - README.md
  - gulpfile.js
  - jekyll-text-theme.gemspec
  - package-lock.json
  - package.json
  - /docs
  - /node_modules
  - /screenshots
  - /test
  - /vendor


## => Plugins
##############################
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jemoji