# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.
#
# ,--------.      ,--.   ,--. ,--.
# '--.  .--',---.  \  `.'  /,-'  '-.
#    |  |  | .-. :  .'    \ '-.  .-'
#    |  |  \   --. /  .'.  \  |  |
#    `--'   `----''--'   '--' `--'

## Base settings ##
# url:  #the base hostname & protocol for your site e.g. https://www.someone.com
baseurl: /
title: IMROK
description: > #this means to ignore newlines until "nav_lists:"
  Hyungrok Kim

nav_lists:
  - titles:
      en: About
      kr: 소개
      zh: 关于
      zh-Hans: 关于
      zh-Hant: 關於
    url: /about.html

# paths:
#   base: /
#   home: /
#   all:  /all.html
#   rss:  /feed.xml

## GitHub repository (if the site is hosted by GitHub) ##
repository: q0115643/q0115643.github.io  #e.g. someone/someone.github.io
repository_tree: master  #e.g. master

## Language & timezone ##
lang: kr #the language of your site, eg: en(English), kr(Korean), zh(简体中文), zh-Hans(简体中文), zh-Hant(繁體中文)
timezone: Asia/Seoul #see https://en.wikipedia.org/wiki/List_of_tz_database_time_zones for the available values

## Author & social ##
author:
  name: 김형록
  email: q0115643@kaist.ac.kr #your Email address e.g. someone@site.com
  facebook: 100004915320124  #your Facebook username
  # twitter:  #your Twitter username
  github: q0115643  #your GitHub username
  # googleplus:  #your Google+ username
  # weibo:  #your Weibo username
  # douban:  #your Douban username
  # linkedin:  #your Linkedin username

## Comment system (Disqus) ##
disqus:
  shortname: rokrokss  #the Disqus shortname for the site

## Comment system (gitalk) ##
# please refer to https://github.com/gitalk/gitalk for more info.
gitalk:
  # clientID:  #Github Application Client ID
  # clientSecret:  #Github Application Client Secret
  # repository:  #Github repo
  # owner:  #Github repo owner
  # admin: #Github repo owner and collaborators, only these guys can initialize github issues, IT IS A LIST.
    # - owner

## Google Analytics ##
ga_tracking_id: UA-111579778-1  #Google analytics id for the site

## Reading quantity (LeanCloud) ##
leancloud:
  app_id: gg2EhhsosMcQOBEApofBaScO-gzGzoHsz  #LeanCloud App id
  app_key: H1s5eqBlwLcHWuma9D8lFajn #LeanCloud App key
  app_class: rokrok #LeanCloud App class

mathjax: true

## Paginate ##
paginate: 5
paginate_path: /blog/page:num

## Post excerpts ##
excerpt_separator: <!--more-->
excerpt_type: html # text | html

## Build ##
markdown: kramdown
highlighter: rouge
permalink: date

exclude:
  - CHANGELOG.md
  - CHECKLIST.md
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README-*.md
  - README.md
  - gulpfile.js
  - jekyll-text-theme.gemspec
  - package-lock.json
  - package.json
  - /docs
  - /node_modules
  - /screenshots
  # - /test
  - /vendor

## Plugins ##
plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate
  - jemoji

## Server ##
server_url: "0.0.0.0"

## Development ##
isdebug: false